### ISSUE TITLE
Doesn't work with stm32duino

### ISSUE THREAD

**Issue by nschurando** [calle-gunnarsson/NexaCtrl#6]
Thanks for the library ! A tiny part of it seems to be avr-specific, and doesn't work when using stm32duino. Might I suggest replace the call to cli() by a call to noInterrupts(), and replacing the include of <avr/interrupt.h> by <Arduino.h> ?

https://github.com/TheCarlG/NexaCtrl/blob/f41fa292f4a54b068830f042fe04cb4b89c1eb23/NexaCtrl.cpp#L162

**Comment by theCarlG** [comment]
If you like you can make a pull request with the change and I'll approve it :)

**Comment by nschurando** [comment]
I quickly tried, but without luck. Because I was in a rush, I ended up using the library referenced here https://charleslabs.fr/fr/project-Contr%C3%B4le+de+prises+DiO+avec+Arduino, in case anyone else is interested. Regards.
